More fixes

diff --git a/.local/bin/hwinfo b/.local/bin/hwinfo
--- a/.local/bin/hwinfo
+++ b/.local/bin/hwinfo
@@ -7,29 +7,31 @@ case $1 in
     case $2 in
     "usage")
         (grep 'cpu ' /proc/stat; sleep 0.1; grep 'cpu ' /proc/stat) | awk -v RS="" '{print ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)"%"}'
-    ;;
+        ;;
     "temp")
         echo $(expr $(cat /sys/devices/platform/nct6775.2592/hwmon/hwmon1/temp2_input) / 1000)°C
-    ;;
+        ;;
     *)
         echo "Invalid metric." && exit 1
-    ;;
+        ;;
     esac
-;;
+    ;;
 "--gpu")
     case $2 in
     "usage")
-        # :(
         #echo $(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)%
-    ;;
+        echo "$(head -n 1 /sys/class/drm/card0/device/gpu_busy_percent)%"
+        ;;
     "temp")
         echo $(sensors amdgpu-pci-1e00 -u | grep temp1_input | awk '{print substr($2,0,2)}')°C
         #echo $(nvidia-smi --query-gpu=temperature.gpu --format=csvnoheader,nounits)°C
-    ;;
+        ;;
     *)
         echo "Invalid metric." && exit 1
-    ;;
+        ;;
     esac
-;;
-*) echo "Invalid resource." && exit 1 ;;
+    ;;
+*) 
+    echo "Invalid resource." && exit 1
+    ;;
 esac
diff --git a/.local/bin/themer b/.local/bin/themer
--- a/.local/bin/themer
+++ b/.local/bin/themer
@@ -19,7 +19,6 @@ function file_view_render() {
 }
 
 function gen_theme() {
-    test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
     nvm use default > /dev/null
     rm $GEN_THEME 2> /dev/null
     
@@ -74,18 +73,21 @@ case $1 in
 "--app-config")
     case $2 in
     "")
-        echo 'Missing parameter.' >&2 && exit 1
+        echo 'Missing parameter.' >&2; exit 1
         ;;
     *)
-        test -f "$2" || echo 'File does not exist.' >&2 && exit 1
-        gen_app_config $2
+        test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
+        ABS_PATH=$(realpath $2)
+        test -f $ABS_PATH || { echo 'File does not exist.' >&2; exit 1; }
+        gen_app_config $ABS_PATH
         ;;
     esac
     ;;
 "--set")
+    test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
     set_theme
     ;;
 *)
-    echo 'Invalid parameter.' >&2 && exit 1
+    echo 'Invalid parameter.' >&2; exit 1
     ;;
 esac
