Use tabs for indentation

diff --git a/.local/bin/themer b/.local/bin/themer
--- a/.local/bin/themer
+++ b/.local/bin/themer
@@ -11,83 +11,83 @@ EXTRA_TMPL="$COLORS_DIR/extra.mustache"
 WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
 
 function stdin_view_render() {
-    echo "$(echo "$1" | mustache - $2)"
+	echo "$(echo "$1" | mustache - $2)"
 }
 
 function file_view_render() {
-    echo "$(mustache $1 $2)"
+	echo "$(mustache $1 $2)"
 }
 
 function gen_theme() {
-    nvm use default > /dev/null
-    rm $GEN_THEME 2> /dev/null
-    
-    local OUTPUT=""
+	nvm use default > /dev/null
+	rm $GEN_THEME 2> /dev/null
 
-    local OPACITY=$(jq -r '.opacity' $CONFIG_FILE)
-    local OPACITY_HEX=$(printf '%x' "$((255*${OPACITY}/100))")
-    local OPACITY_JSON="{ \"percentage\": \"$OPACITY\", \"hex\": \"$OPACITY_HEX\" }"
-    OUTPUT=$(jq ".opacity = $OPACITY_JSON" $CONFIG_FILE)
+	local OUTPUT=""
 
-    local BASE16_THEME=$(jq -r '.colors' $CONFIG_FILE)
-    local COLORS_FILE="${COLORS_DIR}/${BASE16_THEME}.json"
+	local OPACITY=$(jq -r '.opacity' $CONFIG_FILE)
+	local OPACITY_HEX=$(printf '%x' "$((255*${OPACITY}/100))")
+	local OPACITY_JSON="{ \"percentage\": \"$OPACITY\", \"hex\": \"$OPACITY_HEX\" }"
+	OUTPUT=$(jq ".opacity = $OPACITY_JSON" $CONFIG_FILE)
 
-    local HASHLESS_COLORS=$(sed 's/#//' $COLORS_FILE | jq ". += { \"opacity\": $OPACITY_JSON }" -)
-    local EXTRA_COLORS_JSON=$(stdin_view_render "$HASHLESS_COLORS" $EXTRA_TMPL)
+	local BASE16_THEME=$(jq -r '.colors' $CONFIG_FILE)
+	local COLORS_FILE="${COLORS_DIR}/${BASE16_THEME}.json"
 
-    local ALL_COLORS=$(jq ".colors += $EXTRA_COLORS_JSON" $COLORS_FILE)
-    local OUTPUT=$(echo $OUTPUT | jq ". += $ALL_COLORS")
-    local OUTPUT=$(echo $OUTPUT | jq ".colors += { \"scheme\": \"$BASE16_THEME\" }")
+	local HASHLESS_COLORS=$(sed 's/#//' $COLORS_FILE | jq ". += { \"opacity\": $OPACITY_JSON }" -)
+	local EXTRA_COLORS_JSON=$(stdin_view_render "$HASHLESS_COLORS" $EXTRA_TMPL)
 
-    echo "$OUTPUT" | jq 'del(.templates)' > $GEN_THEME
+	local ALL_COLORS=$(jq ".colors += $EXTRA_COLORS_JSON" $COLORS_FILE)
+	local OUTPUT=$(echo $OUTPUT | jq ". += $ALL_COLORS")
+	local OUTPUT=$(echo $OUTPUT | jq ".colors += { \"scheme\": \"$BASE16_THEME\" }")
+
+	echo "$OUTPUT" | jq 'del(.templates)' > $GEN_THEME
 }
 
 function gen_app_config() {
-    local DIR=$(dirname $1)
-    local FILE=$(basename $1)
-    local SOURCE=$(echo "$DIR/$FILE" | envsubst)
-    local TARGET=$(echo "$DIR/${FILE%.*}" | envsubst)
+	local DIR=$(dirname $1)
+	local FILE=$(basename $1)
+	local SOURCE=$(echo "$DIR/$FILE" | envsubst)
+	local TARGET=$(echo "$DIR/${FILE%.*}" | envsubst)
 
-    file_view_render $GEN_THEME $SOURCE > $TARGET
+	file_view_render $GEN_THEME $SOURCE > $TARGET
 }
 
 function set_wallpaper() {
-    feh --no-fehbg --bg-fill "$WALLPAPER_DIR/$(jq -r '.wallpaper' $CONFIG_FILE)"
+	feh --no-fehbg --bg-fill "$WALLPAPER_DIR/$(jq -r '.wallpaper' $CONFIG_FILE)"
 }
 
 function set_theme() {
-    gen_theme
+	gen_theme
 
-    local TEMPLATE_ARR=()
-    read -a TEMPLATE_ARR < <(jq -r '.templates|@tsv' $CONFIG_FILE)
+	local TEMPLATE_ARR=()
+	read -a TEMPLATE_ARR < <(jq -r '.templates|@tsv' $CONFIG_FILE)
 
-    for TMPL in ${TEMPLATE_ARR[@]};
-    do
-        gen_app_config $TMPL
-    done
+	for TMPL in ${TEMPLATE_ARR[@]};
+	do
+		gen_app_config $TMPL
+	done
 
-    set_wallpaper
+	set_wallpaper
 }
 
 case $1 in
 "--app-config")
-    case $2 in
-    "")
-        echo 'Missing parameter.' >&2; exit 1
-        ;;
-    *)
-        test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
-        ABS_PATH=$(realpath $2)
-        test -f $ABS_PATH || { echo 'File does not exist.' >&2; exit 1; }
-        gen_app_config $ABS_PATH
-        ;;
-    esac
-    ;;
+	case $2 in
+	"")
+		echo 'Missing parameter.' >&2; exit 1
+		;;
+	*)
+		test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
+		ABS_PATH=$(realpath $2)
+		test -f $ABS_PATH || { echo 'File does not exist.' >&2; exit 1; }
+		gen_app_config $ABS_PATH
+		;;
+	esac
+	;;
 "--set")
-    test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
-    set_theme
-    ;;
+	test -h "$HOME/.nvm/nvm.sh" && . "$HOME/.nvm/nvm.sh" || exit -1
+	set_theme
+	;;
 *)
-    echo 'Invalid parameter.' >&2; exit 1
-    ;;
+	echo 'Invalid parameter.' >&2; exit 1
+	;;
 esac
