Weekend cleanup!

diff --git a/.config/polybar/scripts/updates b/.config/polybar/scripts/updates
--- a/.config/polybar/scripts/updates
+++ b/.config/polybar/scripts/updates
@@ -2,32 +2,24 @@
 
 [ "$#" -lt 1 ] && echo "Missing parameters." && exit 1
 
-system_output=$(checkupdates)
-aur_output=$(trizen -Qu --aur)
+SYSTEM_OUTPUT=$(checkupdates)
+AUR_OUTPUT=$(trizen -Qu --aur)
 
-system_count=$(echo $system_output | awk 'NF' | wc -l)
-aur_count=$(echo $aur_output | awk 'NF' | wc -l)
+SYSTEM_COUNT=$(echo "$SYSTEM_OUTPUT" | awk NF | wc -l)
+AUR_COUNT=$(echo "$AUR_OUTPUT" | awk NF | wc -l)
 
 case $1 in
-    "count")
-        echo "${system_count}/${aur_count}"
-    ;;
-    "gui")
-        if [ "$system_count" -gt 0 ]; then
-            system_details=$(echo "<b>System</b>\n\n${system_output}")
-        fi
+"count") echo "${SYSTEM_COUNT}/${AUR_COUNT}" ;;
+"gui")
+    SYSTEM_HEADING="<big><b>System</b></big>"
+    AUR_HEADING="<big><b>AUR</b></big>"
+    GAP="\n\n"
+    NO_UPDATES="No updates available"
 
-        if [ "$aur_count" -gt 0 ]; then
-            aur_details=$(echo "<b>AUR</b>\n\n${aur_output}")
-        fi
+    SYSTEM_DETAILS=$([ "$SYSTEM_COUNT" -gt 0 ] && echo "$SYSTEM_OUTPUT" || echo "$NO_UPDATES")
+    AUR_DETAILS=$([ "$AUR_COUNT" -gt 0 ] && echo "$AUR_OUTPUT" || echo "$NO_UPDATES")
 
-        if [ ! -z "$system_count" ] && [ ! -z "$aur_details" ]; then
-            gap="\n\n"
-        fi
-
-        yad --mouse --no-buttons --close-on-unfocus --borders=10 --text="${system_details}${gap}${aur_details}"
-    ;;
-    *)
-        echo "Invalid parameter." && exit 1
-    ;;
+    yad --mouse --no-buttons --close-on-unfocus --borders=10 --text="${SYSTEM_HEADING}${GAP}${SYSTEM_DETAILS}${GAP}${AUR_HEADING}${GAP}${AUR_DETAILS}"
+;;
+*) echo "Invalid parameter." && exit 1 ;;
 esac
diff --git a/.local/bin/hwinfo b/.local/bin/hwinfo
--- a/.local/bin/hwinfo
+++ b/.local/bin/hwinfo
@@ -3,33 +3,31 @@
 [ "$#" -lt 2 ] && echo "Missing parameters." && exit 1
 
 case $1 in
-    "cpu")
-        case $2 in
-            "usage")
-                (grep 'cpu ' /proc/stat; sleep 0.1; grep 'cpu ' /proc/stat) | awk -v RS="" '{print ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)"%"}'
-            ;;
-            "temp")
-                echo $(expr $(cat /sys/devices/platform/nct6775.2592/hwmon/hwmon0/temp2_input) / 1000)°C
-            ;;
-            *)
-                echo "Invalid metric." && exit 1
-            ;;
-        esac
+"--cpu")
+    case $2 in
+    "usage")
+        (grep 'cpu ' /proc/stat; sleep 0.1; grep 'cpu ' /proc/stat) | awk -v RS="" '{print ($13-$2+$15-$4)*100/($13-$2+$15-$4+$16-$5)"%"}'
     ;;
-    "gpu")
-        case $2 in
-            "usage")
-                echo $(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)%
-            ;;
-            "temp")
-                echo $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)°C
-            ;;
-            *)
-                echo "Invalid metric." && exit 1
-            ;;
-        esac
+    "temp")
+        echo $(expr $(cat /sys/devices/platform/nct6775.2592/hwmon/hwmon0/temp2_input) / 1000)°C
     ;;
     *)
-        echo "Invalid resource." && exit 1
+        echo "Invalid metric." && exit 1
     ;;
+    esac
+;;
+"--gpu")
+    case $2 in
+    "usage")
+        echo $(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)%
+    ;;
+    "temp")
+        echo $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)°C
+    ;;
+    *)
+        echo "Invalid metric." && exit 1
+    ;;
+    esac
+;;
+*) echo "Invalid resource." && exit 1 ;;
 esac
