Update configs. Minor fixes

diff --git a/.config/polybar/scripts/weather b/.config/polybar/scripts/weather
--- a/.config/polybar/scripts/weather
+++ b/.config/polybar/scripts/weather
@@ -2,6 +2,8 @@
 
 source ~/.config/color_themes/current
 
+CITY="6092122"
+
 get_icon() {
     case $1 in
         01d) icon="";;
@@ -30,32 +32,43 @@ get_duration() {
     date --date="@$1" +%I:%M
 }
 
-CITY="6092122"
-UNITS="metric"
-SYMBOL="°"
+function get_polybar_text() {
+    UNITS="metric"
+    SYMBOL="°"
 
-current=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$OPW_KEY&id=$CITY&units=$UNITS")
-forecast=$(curl -sf "http://api.openweathermap.org/data/2.5/forecast?APPID=$OPW_KEY&id=$CITY&units=$UNITS&cnt=1")
+    current=$(curl -sf "http://api.openweathermap.org/data/2.5/weather?APPID=$OPW_KEY&id=$CITY&units=$UNITS")
+    forecast=$(curl -sf "http://api.openweathermap.org/data/2.5/forecast?APPID=$OPW_KEY&id=$CITY&units=$UNITS&cnt=1")
 
-if [ ! -z "$current" ] && [ ! -z "$forecast" ]; then
-    current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
-    current_icon=$(echo "$current" | jq -r ".weather[].icon")
+    if [ ! -z "$current" ] && [ ! -z "$forecast" ]; then
+        current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
+        current_icon=$(echo "$current" | jq -r ".weather[].icon")
 
-    forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
-    forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[].icon")
+        forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
+        forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[].icon")
 
-    if [ "$current_temp" -gt "$forecast_temp" ]; then
-        trend=""
-    elif [ "$forecast_temp" -gt "$current_temp" ]; then
-        trend=""
+        if [ "$current_temp" -gt "$forecast_temp" ]; then
+            trend=""
+        elif [ "$forecast_temp" -gt "$current_temp" ]; then
+            trend=""
+        else
+            trend=""
+        fi
+
+        sun_rise=" $(get_duration "$(echo "$current" | jq ".sys.sunrise")")"
+        sun_set=" $(get_duration "$(echo "$current" | jq ".sys.sunset")")"
+
+        echo "$(get_icon "$current_icon") $current_temp$SYMBOL  $trend  $(get_icon "$forecast_icon") $forecast_temp$SYMBOL   $sun_rise   $sun_set"
     else
-        trend=""
+        echo "%{F$BASE02} Unable to get forecast%{F-}"
     fi
+}
 
-    sun_rise=" $(get_duration "$(echo "$current" | jq ".sys.sunrise")")"
-    sun_set=" $(get_duration "$(echo "$current" | jq ".sys.sunset")")"
+function open_browser() {
+    xdg-open "https://openweathermap.org/city/${CITY}"
+}
 
-    echo "$(get_icon "$current_icon") $current_temp$SYMBOL  $trend  $(get_icon "$forecast_icon") $forecast_temp$SYMBOL   $sun_rise   $sun_set"
-else
-    echo "%{F$BASE02} Unable to get forecast%{F-}"
-fi
+case $1 in
+"-p") get_polybar_text ;;
+"-o") open_browser ;;
+*) echo "Invalid parameter." && exit 1 ;;
+esac
